Add syntax highlight support for zeek and sig
bbannier/zeek-language-server pull request #11
Opened 2022-07-20 12:44 UTC by AmazingPP

Better syntax highlighting than  [bro/zeek - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=aeppert.bro)

<img width="1440" alt="QQ20220720-204210@2x" src="https://user-images.githubusercontent.com/30434507/179984806-0fdecac9-54f6-4b3f-b569-9c7df627bc52.png">

> [syntax_test.zeek.zip](https://github.com/bbannier/zeek-language-server/files/9149775/syntax_test.zeek.zip)

2022-07-20 14:07 UTC, bbannier commented
This is great, but like I mentioned offline probably out of scope for this extension. I think this would fit much better as a patch for https://github.com/aeppert/bro-vsc-extension which seems to be _the syntax highlighting extensions for Zeek_ for vscode. Could you please try to get a PR into that extension first? If the author is unresponsive we could revisit pulling vscode only syntax it into this extension. In any case, we could add a dependencies to it to make this extension more useful out of the box (i.e., add `﻿"extensionDependencies": ["aeppert.bro"]` to `package.json`).

If we'd implement it here I would much rather see us implement support for [LSP semantic tokens](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_semanticTokens) (probably support for the `full` flavor might be good enough).

2022-07-21 07:20 UTC, AmazingPP commented
In fact, I created RP ([New features](https://github.com/aeppert/bro-vsc-extension/pull/4)) four months ago for [bro-vsc-extension](https://github.com/aeppert/bro-vsc-extension), but no one replied to me.

I think syntax highlight and semantic highlight can exist at the same time. When LSP is not working, syntax highlight can provide basic highlight. Just like this extension [F# Language Server](https://github.com/georgewfraser/fsharp-language-server)

When LSP works normally, semantic highlight can provide better highlight than syntax highlight. because The editor applies the highlighting from semantic tokens on top of the highlighting from grammars.

2022-07-21 08:01 UTC, bbannier requested changes
> In fact, I created RP (https://github.com/aeppert/bro-vsc-extension/pull/4) four months ago for [bro-vsc-extension](https://github.com/aeppert/bro-vsc-extension), but no one replied to me.

Fair enough, let's then merge this into this one.

I left a couple of mostly minor comments; would be great if you could have a look.

The pre-commit hook CI also flagged a couple of formatting issues which should be easy to fix by either copying the feedback from CI or by running `pre-commit` locally (you can disable checks which need Rust by running `SKIP=fmt,clippy,cargo-check pre-commit run  -a`).

2022-07-21 08:03 UTC, bbannier commented on vscode/syntaxes/zeek.json
> +{
```suggestion
{
    "$schema": "https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json",
```

2022-07-21 13:52 UTC, AmazingPP commented on vscode/syntaxes/sig.json
> +    "uuid": "d8db6740-ccd9-4e4a-9da3-8a3cf2313389",
The UUIDs were mainly used by TextMate to classify which file was a part of which bundle.

https://macromates.com/textmate/manual/bundles

2022-07-21 14:03 UTC, AmazingPP commented on vscode/syntaxes/zeek.json
> +    "uuid": "d27211b1-e07c-4c8d-9d7e-13daa805693c",
https://github.com/bbannier/zeek-language-server/pull/11#discussion_r926702994

2022-07-21 16:58 UTC, bbannier commented on vscode/syntaxes/sig.json
> +    "uuid": "d8db6740-ccd9-4e4a-9da3-8a3cf2313389",
I'd suggest to drop them until we figure out a need.

2022-07-22 06:40 UTC, merged